
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ibm-icp-management
    name: fandon-jenkins
  namespace: jx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: fandon-jenkins
          servicePort: 8080
        path: /jenkins
